#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.0.33-0ubuntu0.1

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend orinaverses.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 100.26.153.246
        server 64820-web-02 100.25.190.67
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
